"use client";
/* eslint-disable react-hooks/set-state-in-effect */

import Link from "next/link";
import {useEffect,useMemo,useState} from "react";

type Ticket={id:string;subject:string;status:string;created_at:string};
const help=[
 {title:"How XP works",body:"XP records real completed effort. The server calculates awards from activities, quests, and habits; corrections create ledger reversals instead of rewriting history."},
 {title:"Goals and skills are different",body:"A goal is an outcome you are pursuing. A skill is a capability that persists when a goal is paused, completed, abandoned, or replaced."},
 {title:"Changing a goal",body:"Open the goal and use Manage goal to revise its target, deadline, priority, or state. SkillTree keeps the revision history and never removes previously earned skills."},
 {title:"Privacy and evidence",body:"Your account, goals, activity, journal, and evidence are private by default. Public profiles contain only the snapshot fields you explicitly choose to publish."},
 {title:"Subscriptions",body:"A paid plan unlocks product tools and higher limits, never XP, levels, or achievements. Billing state and entitlements are verified by the server."},
 {title:"Imports and integrations",body:"CSV imports are previewed before confirmation and deduplicated under retries. Disconnecting an integration preserves the historical activities already imported."},
];

export default function SupportPage(){
 const [tickets,setTickets]=useState<Ticket[]>([]),[message,setMessage]=useState(""),[saving,setSaving]=useState(false),[loading,setLoading]=useState(true),[failed,setFailed]=useState(false),[signedIn,setSignedIn]=useState<boolean|null>(null),[query,setQuery]=useState(""),[diagnosticId,setDiagnosticId]=useState("");
 const filtered=useMemo(()=>{const value=query.trim().toLowerCase();return value?help.filter(item=>`${item.title} ${item.body}`.toLowerCase().includes(value)):help},[query]);
 const load=()=>{setLoading(true);return fetch("/api/v1/support").then(async response=>{if(response.status===401){setSignedIn(false);setFailed(false);setTickets([]);return null}setSignedIn(true);if(!response.ok)throw new Error();return response.json()}).then(body=>{if(body){setTickets(body.data||[]);setFailed(false)}}).catch(()=>setFailed(true)).finally(()=>setLoading(false))};
 useEffect(()=>{setDiagnosticId(crypto.randomUUID());void load()},[]);
 const submit=async(form:FormData)=>{setSaving(true);setMessage("");try{const diagnostics=form.get("diagnostics")==="on"?{diagnosticId,route:location.pathname,release:document.documentElement.dataset.release||"unknown",userAgent:navigator.userAgent}:undefined,response=await fetch("/api/v1/support",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({subject:form.get("subject"),message:form.get("message"),category:form.get("category"),diagnostics})}),body=await response.json().catch(()=>null);setSaving(false);if(!response.ok){setMessage(body?.error?.message||"Your request could not be sent.");return}setMessage(`Your feedback was received. Diagnostic ID: ${diagnosticId}`);await load()}catch{setSaving(false);setMessage("Your request could not be sent. Check your connection and try again.")}};
 const copyDiagnostic=async()=>{try{await navigator.clipboard.writeText(diagnosticId);setMessage("Diagnostic ID copied.")}catch{setMessage("Select the diagnostic ID and copy it manually.")}};
 return <main className="onboard"><header><Link href={signedIn?"/app":"/"} className="onboard-logo">SkillTree IRL</Link><Link href={signedIn?"/app":"/sign-in"}>{signedIn?"Back to app":"Sign in"}</Link></header><section><div className="onboard-card"><p className="kicker">HELP & SUPPORT</p><h1>How can we help?</h1><p>Search practical guidance or contact support from your signed-in account. Never include passwords, recovery codes, payment-card details, or access tokens.</p>
 <label className="search">Search help<input aria-label="Search help" value={query} onChange={event=>setQuery(event.target.value)} placeholder="XP, privacy, changing goals, imports…"/></label>
 <div className="detail-grid"><section><h2>Help centre</h2>{filtered.length?filtered.map(item=><details className="card side-card" key={item.title}><summary>{item.title}</summary><p>{item.body}</p></details>):<div className="empty"><h2>No matching help</h2><p>Try a broader term or contact support.</p></div>}</section>
 <section>{loading?<div className="live-loading" role="status" aria-label="Checking support access"><i/><i/><i/></div>:signedIn?<><form className="real-form card side-card" action={submit}><h2>Contact support</h2><label>Category<select name="category" defaultValue="bug"><option value="bug">Bug</option><option value="feature_request">Feature request</option><option value="confusing">Confusing</option><option value="other">Other</option></select></label><label>Subject<input name="subject" minLength={3} maxLength={160} required/></label><label>Details<textarea name="message" minLength={10} maxLength={5000} required/></label><label><input name="diagnostics" type="checkbox"/> Include browser, app release, current page, and diagnostic ID</label>{message&&<p className="modal-tip" role="status">{message}</p>}<button className="continue" disabled={saving}>{saving?"Sending…":"Send feedback"}</button></form>{failed?<div className="empty" role="alert"><h2>Your support history is temporarily unavailable</h2><p>Existing requests have not been removed.</p><button className="primary" onClick={load}>Try again</button></div>:tickets.length?<div className="card side-card"><h2>Your requests</h2>{tickets.map(ticket=><p key={ticket.id}><b>{ticket.subject}</b><br/><small>{ticket.status} · {new Date(ticket.created_at).toLocaleDateString()}</small></p>)}</div>:<p>You have no support requests yet.</p>}</>:<div className="card side-card"><h2>Contact support securely</h2><p>Sign in so we can keep your request and its replies private and associate diagnostics with the correct account.</p><Link className="primary" href={`/sign-in?next=${encodeURIComponent("/support")}`}>Sign in to contact support</Link><h3>Diagnostic ID</h3><p>Share this identifier when reporting a sign-in or recovery problem through the published support contact.</p><label>Diagnostic ID<input readOnly value={diagnosticId}/></label><button className="outline" onClick={copyDiagnostic}>Copy diagnostic ID</button>{message&&<p role="status">{message}</p>}</div>}</section></div>
 </div></section></main>;
}
