import {describe,expect,it} from "vitest";
import {hasSupabaseSessionCookie,isAllowedMutationOrigin,rateLimitPolicy} from "./request";
describe("request security",()=>{
  it("recognises Supabase sessions",()=>expect(hasSupabaseSessionCookie(["theme","sb-project-auth-token"])).toBe(true));
  it("rejects cross-site and mismatched-origin mutations",()=>{const base={method:"POST",pathname:"/app",requestOrigin:"https://skilltree.example",appOrigin:"https://skilltree.example",hasSessionCookie:true};expect(isAllowedMutationOrigin({...base,origin:"https://evil.example",secFetchSite:"cross-site"})).toBe(false);expect(isAllowedMutationOrigin({...base,origin:"https://evil.example",secFetchSite:"same-site"})).toBe(false)});
  it("accepts same-origin mutations and signed callbacks",()=>{const base={method:"POST",requestOrigin:"https://skilltree.example",appOrigin:"https://skilltree.example",hasSessionCookie:true};expect(isAllowedMutationOrigin({...base,pathname:"/app",origin:"https://skilltree.example",secFetchSite:"same-origin"})).toBe(true);expect(isAllowedMutationOrigin({...base,pathname:"/api/stripe/webhook",origin:null,secFetchSite:null})).toBe(true)});
  it("requires an origin with an auth cookie",()=>expect(isAllowedMutationOrigin({method:"DELETE",pathname:"/api/v1/account",origin:null,secFetchSite:null,requestOrigin:"https://skilltree.example",hasSessionCookie:true})).toBe(false));
  it("covers required abuse surfaces",()=>{expect(rateLimitPolicy("POST","/sign-in")?.scope).toBe("authentication");expect(rateLimitPolicy("POST","/recover")?.scope).toBe("password-recovery");expect(rateLimitPolicy("POST","/api/v1/evidence/upload")?.scope).toBe("evidence-upload");expect(rateLimitPolicy("GET","/api/v1/search")?.scope).toBe("search");expect(rateLimitPolicy("GET","/u/alex")?.scope).toBe("public-profile");expect(rateLimitPolicy("GET","/r/invite")?.scope).toBe("public-invitation");expect(rateLimitPolicy("POST","/api/v1/integrations/github/callback")?.scope).toBe("integration-callback");expect(rateLimitPolicy("PATCH","/api/v1/goals/1")?.scope).toBe("api-mutation")});
});
