import {authenticated,failure} from "@/domains/shared/http";
const escape=(value:unknown)=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&apos;"}[char]||char));
export async function GET(request:Request){
 const auth=await authenticated();if("error" in auth)return auth.error;const url=new URL(request.url),type=url.searchParams.get("type")||"character",id=url.searchParams.get("id"),format=url.searchParams.get("format")||"square",sizes:Record<string,[number,number]>={square:[1080,1080],portrait:[1080,1350],landscape:[1200,630]},[width,height]=sizes[format]||sizes.square;
 const [profile,summary]=await Promise.all([auth.supabase.from("profiles").select("display_name,accent").single(),auth.supabase.from("user_progress_summary").select("lifetime_xp,discovered_skills,lifetime_activities").single()]);if(profile.error||summary.error)return failure(profile.error||summary.error);let eyebrow="MY SKILLTREE",title=`${profile.data.display_name}'s character`,stat=`${Number(summary.data.lifetime_xp).toLocaleString()} XP`,detail=`${summary.data.discovered_skills} skills · ${summary.data.lifetime_activities} meaningful actions`;
 if(type==="skill"&&id){const skill=await auth.supabase.from("skill_xp_totals").select("name,category,lifetime_xp").eq("skill_id",id).single();if(skill.error)return failure(skill.error);eyebrow="SKILL LEVEL";title=skill.data.name;stat=`${Number(skill.data.lifetime_xp).toLocaleString()} XP`;detail=skill.data.category}
 if(type==="achievement"&&id){const achievement=await auth.supabase.from("achievement_unlocks").select("achievement_key,unlocked_at").eq("id",id).single();if(achievement.error)return failure(achievement.error);eyebrow="ACHIEVEMENT UNLOCKED";title=achievement.data.achievement_key.replaceAll("_"," ");stat="◆";detail=`Unlocked ${new Intl.DateTimeFormat("en-GB").format(new Date(achievement.data.unlocked_at))}`}
 if(type==="season"){const season=await auth.supabase.from("season_user_stats").select("xp_earned,activities,quests_completed,habits_completed,seasons(name)").order("updated_at",{ascending:false}).limit(1).maybeSingle();if(season.error)return failure(season.error);if(season.data){eyebrow="SEASON COMPLETE";title=(season.data.seasons as unknown as {name:string}|null)?.name||"Current season";stat=`${Number(season.data.xp_earned).toLocaleString()} XP`;detail=`${season.data.activities} activities · ${season.data.quests_completed} quests · ${season.data.habits_completed} habits`}}
 const accent=/^#[0-9a-f]{6}$/i.test(profile.data.accent)?profile.data.accent:"#7465e8",svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}"><defs><linearGradient id="bg" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#151426"/><stop offset="1" stop-color="#25204a"/></linearGradient></defs><rect width="100%" height="100%" rx="48" fill="url(#bg)"/><circle cx="${width*.82}" cy="${height*.2}" r="${Math.min(width,height)*.22}" fill="${accent}" opacity=".24"/><circle cx="${width*.15}" cy="${height*.84}" r="${Math.min(width,height)*.16}" fill="${accent}" opacity=".16"/><text x="${width*.1}" y="${height*.16}" fill="${accent}" font-family="system-ui,sans-serif" font-size="28" font-weight="700" letter-spacing="5">${escape(eyebrow)}</text><text x="${width*.1}" y="${height*.38}" fill="#fff" font-family="system-ui,sans-serif" font-size="${Math.round(width*.064)}" font-weight="750">${escape(title)}</text><text x="${width*.1}" y="${height*.57}" fill="#fff" font-family="system-ui,sans-serif" font-size="${Math.round(width*.09)}" font-weight="800">${escape(stat)}</text><text x="${width*.1}" y="${height*.69}" fill="#cbc8df" font-family="system-ui,sans-serif" font-size="30">${escape(detail)}</text><text x="${width*.1}" y="${height*.88}" fill="#fff" font-family="system-ui,sans-serif" font-size="26" font-weight="700">SkillTree IRL · Real progress, permanently yours</text></svg>`;
 return new Response(svg,{headers:{"content-type":"image/svg+xml; charset=utf-8","content-disposition":`attachment; filename="skilltree-${type}-${format}.svg"`,"cache-control":"private, no-store"}});
}
