import {notFound} from "next/navigation";
import {createClient} from "@/lib/supabase/server";
import {Award,Leaf,Sparkles,Target,Zap} from "lucide-react";
import "./public.css";
type Summary={lifetimeXp?:number;discoveredSkills?:number;lifetimeActivities?:number};
type SharedSkill={name:string;category:string;lifetime_xp:number};
type SharedGoal={title:string;category:string;currentValue:number;targetValue:number;unit:string};
export default async function PublicProfile({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;const supabase=await createClient();if(!supabase)throw new Error("Public profile service is not configured");
 const {data:profile,error:profileError}=await supabase.from("profiles").select("id,display_name,bio,accent,visibility").eq("public_slug",slug).in("visibility",["public","unlisted"]).maybeSingle();if(profileError)throw new Error("Public profile could not be loaded",{cause:profileError});if(!profile)notFound();
 const {data:snapshot,error:snapshotError}=await supabase.from("public_profile_snapshots").select("summary,skills,focus_goals,achievements").eq("user_id",profile.id).maybeSingle();if(snapshotError)throw new Error("Public profile snapshot could not be loaded",{cause:snapshotError});
 const summary=(snapshot?.summary||{}) as Summary,skills=(snapshot?.skills||[]) as SharedSkill[],goals=(snapshot?.focus_goals||[]) as SharedGoal[],achievements=(snapshot?.achievements||[]) as Array<{key:string}>;
 return <main className="public-profile" style={{"--profile-accent":profile.accent} as React.CSSProperties}><header><div className="public-logo"><Leaf/> SkillTree <em>IRL</em></div><a href="/sign-in?mode=signup">Create your SkillTree</a></header><section className="public-hero"><div className="public-avatar">{profile.display_name.slice(0,2).toUpperCase()}</div><p>CHARACTER PROFILE</p><h1>{profile.display_name}</h1><span>{profile.bio||"Building a life through meaningful progress."}</span></section><div className="public-stats"><div><Zap/><b>{Number(summary.lifetimeXp||0).toLocaleString()}</b><small>Lifetime XP</small></div><div><Sparkles/><b>{summary.discoveredSkills||0}</b><small>Skills discovered</small></div><div><Target/><b>{goals.length}</b><small>Focus goals</small></div><div><Award/><b>{achievements.length}</b><small>Featured achievements</small></div></div><section className="public-grid"><div className="public-card"><h2>Strongest skills</h2>{skills.map(skill=><div className="public-skill" key={skill.name}><span>{skill.name.slice(0,1)}</span><div><b>{skill.name}</b><small>{skill.category}</small></div><em>{Number(skill.lifetime_xp).toLocaleString()} XP</em></div>)}</div><div className="public-card"><h2>Current focus</h2>{goals.map(goal=><div className="public-goal" key={goal.title}><b>{goal.title}</b><small>{goal.category}</small><div><i style={{width:`${Math.min(100,Number(goal.currentValue)/Number(goal.targetValue||100)*100)}%`}}/></div></div>)}</div></section><footer>Only information {profile.display_name} chose to share is shown here.</footer></main>
}
