import type {Metadata} from "next";import {notFound} from "next/navigation";import {MarketingPage} from "@/components/marketing";
const topics={
 "goal-tracking":{title:"Goal tracking that preserves the whole journey",intro:"A useful goal system must handle changing targets, quiet periods and completed chapters without deleting the record.",sections:["Choose a measurement that fits the outcome","Record progress as an append-only history","Revise, pause and archive without punishment"]},
 "skill-development":{title:"Skill development through meaningful action",intro:"Capabilities grow through what you actually do. SkillTree connects practice to a permanent, inspectable progression record.",sections:["Link activities to lasting skills","Keep XP source-backed and reversible","See development across changing goals"]},
 "real-life-rpg":{title:"A real-life RPG without fake progress",intro:"Game language can make growth visible without turning life into a grind or selling status.",sections:["XP only follows real action","Levels never gate essential functionality","Achievements remember meaningful moments"]},
 "personal-skill-tree":{title:"How a personal skill tree grows",intro:"A personal SkillTree is a map of capabilities you have developed—not a fixed course someone else chose for you.",sections:["Create and discover your own branches","Organise, relate and safely merge skills","Browse hundreds of nodes clearly"]},
 "habit-progression":{title:"Habit progression without streak punishment",intro:"Recurring practice should build momentum while leaving room for illness, travel and ordinary life.",sections:["Schedule in your own timezone","Log complete, partial or skipped occurrences","Keep streaks secondary to lifetime growth"]},
 "life-goals":{title:"Life goals need room to change",intro:"Some outcomes are measurable; others are directions. Both deserve structure without forced deadlines or false precision.",sections:["Use open-ended goals when completion is not the point","Break complexity into milestones and dependencies","Review direction without rewriting history"]},
 "progress-tracking":{title:"Progress tracking you can trust",intro:"Useful progress is a durable event trail with clear sources, safe corrections and insight that does not overclaim.",sections:["Append events instead of overwriting totals","Use reversal entries for corrections","Turn history into momentum and forecast ranges"]}
} as const;
export function generateStaticParams(){return Object.keys(topics).map(slug=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params,topic=topics[slug as keyof typeof topics];if(!topic)return{};return{title:topic.title,description:topic.intro,alternates:{canonical:`/learn/${slug}`}}}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params,topic=topics[slug as keyof typeof topics];if(!topic)notFound();return <MarketingPage eyebrow="SKILLTREE GUIDE" title={topic.title} intro={topic.intro} sections={topic.sections.map((title,index)=>({title,body:["SkillTree supports this directly through flexible goals, authoritative event history and progressive disclosure.","Private-by-default records and server-enforced integrity keep the result grounded in real work.","The interface stays useful for a first goal and for years of accumulated character history."][index]}))}/>}
