"use client";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {useEffect,useState} from "react";

type Template={id:string;owner_id:string|null;template_type:"goal"|"skill_tree";name:string;description:string|null;category:string;visibility:string;definition:{milestones?:string[];skills?:Array<string|{name:string;children?:string[]}>;quests?:string[]};uses:number};

export default function Templates(){
 const router=useRouter(),[templates,setTemplates]=useState<Template[]>([]),[filter,setFilter]=useState("all"),[message,setMessage]=useState(""),[loading,setLoading]=useState(true),[failed,setFailed]=useState(false);
 const fetchTemplates=(type=filter)=>{setLoading(true);return fetch(`/api/v1/templates${type==="all"?"":`?type=${type}`}`).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(body=>{setTemplates(body.data||[]);setFailed(false)}).catch(()=>setFailed(true)).finally(()=>setLoading(false))};
 useEffect(()=>{fetch("/api/v1/templates").then(r=>{if(!r.ok)throw new Error();return r.json()}).then(body=>{setTemplates(body.data||[]);setFailed(false)}).catch(()=>setFailed(true)).finally(()=>setLoading(false))},[]);
 const changeFilter=(type:string)=>{setFilter(type);fetchTemplates(type)};
 const applyTemplate=async(template:Template)=>{const response=await fetch(`/api/v1/templates/${template.id}/instantiate`,{method:"POST",headers:{"content-type":"application/json"},body:"{}"}),body=await response.json().catch(()=>null);setMessage(response.ok?`${template.name} added to your SkillTree.`:body?.error?.message||"Template could not be added.");if(response.ok)setTimeout(()=>router.push("/app"),700)};
 const create=async(form:FormData)=>{let definition:unknown;try{definition=JSON.parse(String(form.get("definition")||""))}catch{return setMessage("The reusable structure must be valid JSON.")}const response=await fetch("/api/v1/templates",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({templateType:form.get("templateType"),name:form.get("name"),description:form.get("description"),category:form.get("category"),visibility:form.get("visibility"),definition})}),body=await response.json().catch(()=>null);setMessage(response.ok?"Template saved.":body?.error?.message||"Template could not be saved.");if(response.ok)fetchTemplates()};
 return <main className="onboard"><header><Link href="/app" className="onboard-logo">SkillTree IRL</Link><Link href="/app">Back to app</Link></header><section><div className="onboard-card"><p className="kicker">REUSABLE PATHS</p><h1>Templates</h1><p>Start from a useful structure, then change anything. Templates never own or constrain your personal data.</p>{message&&<p className="modal-tip" role="status">{message}</p>}
  <div className="tabs"><button className={filter==="all"?"active":""} onClick={()=>changeFilter("all")}>All</button><button className={filter==="goal"?"active":""} onClick={()=>changeFilter("goal")}>Goals</button><button className={filter==="skill_tree"?"active":""} onClick={()=>changeFilter("skill_tree")}>Skill trees</button></div>
  {loading?<div className="empty" role="status"><h2>Loading templates…</h2></div>:failed?<div className="empty" role="alert"><h2>Templates are temporarily unavailable</h2><p>Your SkillTree has not changed. Check your connection and try again.</p><button className="primary" onClick={()=>fetchTemplates(filter)}>Try again</button></div>:<div className="goal-grid">{templates.map(template=><article className="card side-card" key={template.id}><small>{template.owner_id?"COMMUNITY":"CURATED"} · {template.category}</small><h2>{template.name}</h2><p>{template.description}</p><p>{template.template_type==="goal"?`${template.definition.milestones?.length||0} milestones · ${template.definition.quests?.length||0} quests`:`${template.definition.skills?.length||0} skill branches`} · used {template.uses} times</p><button className="primary" onClick={()=>applyTemplate(template)}>Add to my SkillTree</button></article>)}</div>}
  <details className="card side-card"><summary>Create your own template</summary><form className="real-form" action={create}><div className="form-row"><label>Type<select name="templateType"><option value="goal">Goal</option><option value="skill_tree">Skill tree</option></select></label><label>Visibility<select name="visibility"><option value="private">Private</option><option value="unlisted">Unlisted</option><option value="public">Public (moderated)</option></select></label></div><label>Name<input name="name" required maxLength={120}/></label><div className="form-row"><label>Category<input name="category" defaultValue="Other"/></label><label>Description<input name="description" maxLength={500}/></label></div><label>Reusable structure (JSON)<textarea name="definition" required defaultValue={'{"goal":{"title":"My reusable goal","measurement":"open_ended"},"milestones":[],"skills":[],"quests":[]}'}/></label><button className="primary">Save template</button></form></details>
 </div></section></main>;
}
