"use client";
import {useEffect,useState} from "react";import {Check,Pause,Play,X} from "lucide-react";import {attachActivityEvidence} from "@/lib/evidence/attach-client";
type Props={id:string;title:string;startedAt:string;status:"running"|"paused";activeSeconds:number;segmentStartedAt:string|null;onClose:()=>void;onDone:(message:string)=>void};
export default function FocusSession({id,title,status:initialStatus,activeSeconds,segmentStartedAt,onClose,onDone}:Props){
 const [status,setStatus]=useState(initialStatus),[seconds,setSeconds]=useState(()=>activeSeconds+(initialStatus==="running"&&segmentStartedAt?Math.max(0,Math.floor((Date.now()-new Date(segmentStartedAt).getTime())/1000)):0)),[saving,setSaving]=useState(false),[error,setError]=useState(""),[finishing,setFinishing]=useState(false);
 useEffect(()=>{if(status!=="running")return;const timer=setInterval(()=>setSeconds(value=>value+1),1000);return()=>clearInterval(timer)},[status]);
 const transition=async(action:"pause"|"resume"|"complete"|"cancel",form?:FormData)=>{setSaving(true);setError("");try{const response=await fetch(`/api/v1/focus-sessions/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action,description:form?.get("description"),result:form?.get("result")})}),body=await response.json().catch(()=>null);if(!response.ok){setError(body?.error?.message||"The focus session could not be updated.");setSaving(false);return}if(action==="pause"||action==="resume"){setStatus(body.data.status);setSeconds(Number(body.data.active_seconds||seconds));setSaving(false);return}if(action==="complete"&&form&&body.data.activity_id){try{await attachActivityEvidence(body.data.activity_id,form)}catch(e){onDone(e instanceof Error?e.message:"Focus activity saved without evidence.");onClose();return}}onDone(action==="complete"?"Focus session saved as an activity with private evidence.":"Focus session discarded. No activity or XP was created.");onClose()}catch{setError("The focus session could not be updated. Check your connection and try again.");setSaving(false)}};
 const minutes=Math.floor(seconds/60),remaining=seconds%60;
 return <div className="modal-wrap"><div className="quick-modal" role="dialog" aria-modal="true" aria-label={`Focus session: ${title}`}><div className="modal-head"><div><span className="eyebrow">FOCUS SESSION · {status.toUpperCase()}</span><h2>{title}</h2></div><button className="icon-btn" disabled={saving} onClick={()=>transition("cancel")} aria-label="Discard focus session"><X/></button></div><div className="empty">{status==="paused"?<Play/>:<Pause/>}<h2 aria-live="off">{String(minutes).padStart(2,"0")}:{String(remaining).padStart(2,"0")}</h2><p>Only active time is counted. Finishing creates a private activity; it does not award XP by itself.</p>{error&&<p className="form-error" role="alert">{error}</p>}<div className="form-actions"><button className="outline" disabled={saving} onClick={()=>transition(status==="running"?"pause":"resume")}>{status==="running"?<><Pause/> Pause</>:<><Play/> Resume</>}</button><button className="primary" disabled={saving} onClick={()=>setFinishing(true)}><Check/> Finish</button></div></div>{finishing&&<form className="real-form card side-card" action={form=>transition("complete",form)}><label>What did you work on?<input name="description" defaultValue={title} maxLength={500} required/></label><label>Result or private note<textarea name="result" maxLength={2000}/></label><details><summary>Private evidence (optional)</summary><div className="evidence-fields"><label>Photo or document<input name="evidenceFile" type="file" accept="image/jpeg,image/png,image/webp,application/pdf,text/plain"/></label><label>Secure web link<input name="evidenceUrl" type="url" pattern="https://.*" placeholder="https://…"/></label><label>Evidence note<textarea name="evidenceText" maxLength={2000}/></label></div></details><div className="form-actions"><button type="button" className="outline" onClick={()=>setFinishing(false)}>Back</button><button className="primary" disabled={saving}>{saving?"Saving…":"Create activity"}</button></div></form>}</div></div>;
}
