"use client";
import {useState} from "react";import {Check,X} from "lucide-react";import type {GoalItem} from "@/app/page";
type GoalState="active"|"focus"|"later"|"paused"|"completed"|"abandoned"|"archived";
export default function GoalManageDialog({goal,close,onSaved}:{goal:GoalItem;close:()=>void;onSaved:(goal:GoalItem|null)=>void}){
 const [saving,setSaving]=useState(false),[error,setError]=useState("");
 const fail=async(response:Response)=>{const body=await response.json().catch(()=>({}));setError(body.error?.message||"The goal could not be updated.");setSaving(false)};
 const submit=async(form:FormData)=>{
  setSaving(true);setError("");const title=String(form.get("title")||"").trim(),category=String(form.get("category")||"Other").trim(),target=form.get("target")?Number(form.get("target")):goal.target,unit=String(form.get("unit")||"").trim(),deadlineValue=String(form.get("deadline")||""),status=String(form.get("status")||"active") as GoalState,priority=String(form.get("priority")||goal.priority||"normal"),reason=String(form.get("reason")||"Goal updated by user");
  const editResponse=await fetch(`/api/v1/goals/${goal.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({title,category,priority,deadline:deadlineValue?new Date(`${deadlineValue}T12:00:00`).toISOString():null})});if(!editResponse.ok)return fail(editResponse);
  if(goal.target>0&&(target!==goal.target||unit!==goal.unit)){const response=await fetch(`/api/v1/goals/${goal.id}/target`,{method:"POST",headers:{"content-type":"application/json","idempotency-key":crypto.randomUUID()},body:JSON.stringify({target,unit,currency:/^[A-Z]{3}$/.test(unit)?unit:null,reason})});if(!response.ok)return fail(response)}
  if(status!==goal.status.toLowerCase()){const response=await fetch(`/api/v1/goals/${goal.id}/state`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({status,reason})});if(!response.ok)return fail(response)}
  const staysVisible=["active","focus"].includes(status);onSaved(staysVisible?{...goal,title,category,target,unit,priority:priority as GoalItem["priority"],status:status==="focus"?"Focus":"Active",deadline:deadlineValue?new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short"}).format(new Date(`${deadlineValue}T12:00:00`)):"No deadline"}:null);close();
 };
 return <div className="modal-wrap" onMouseDown={event=>event.target===event.currentTarget&&close()}><div className="quick-modal" role="dialog" aria-modal="true" aria-label="Edit goal"><div className="modal-head"><div><span className="eyebrow">GOAL SETTINGS</span><h2>Edit goal</h2></div><button className="icon-btn" aria-label="Close goal settings" onClick={close}><X/></button></div><form className="real-form" action={submit}>
  <label>Title<input name="title" defaultValue={goal.title} required maxLength={180}/></label>
  <div className="form-row"><label>Category<input name="category" defaultValue={goal.category} required/></label><label>State<select name="status" defaultValue={goal.status.toLowerCase()}><option value="focus">Focus</option><option value="active">Active</option><option value="later">Later</option><option value="paused">Paused</option><option value="completed">Completed</option><option value="abandoned">Abandoned</option><option value="archived">Archived</option></select></label></div>
  <div className="form-row"><label>Priority<select name="priority" defaultValue={goal.priority||"normal"}><option value="focus">Focus</option><option value="high">High</option><option value="normal">Normal</option><option value="low">Low</option><option value="later">Later</option></select></label><label>Deadline<input name="deadline" type="date"/></label></div>
  {goal.target>0&&<div className="form-row"><label>Target<input name="target" type="number" min="0.000001" step="any" defaultValue={goal.target} required/></label><label>Unit<input name="unit" defaultValue={goal.unit} maxLength={30}/></label></div>}
  <label>Reason for this change<textarea name="reason" maxLength={1000} placeholder="Keeps your goal history understandable"/></label>{error&&<div className="form-error" role="alert">{error}</div>}<div className="form-actions"><button type="button" className="outline" onClick={close}>Cancel</button><button className="primary" disabled={saving}>{saving?"Saving…":<><Check/> Save changes</>}</button></div>
 </form></div></div>;
}
