"use client";

import {useCallback,useEffect,useState} from "react";
import {Check,Plus,Sparkles,Trash2} from "lucide-react";

type GoalContext={
  goal_milestones?:Array<{id:string;title:string;completed_at:string|null}>;
  goal_skill_links?:Array<{skill_id:string;weight:number;skills:{name?:string;category?:string}|null}>;
  goal_reviews?:Array<{id:string;summary:string|null;momentum:string|null;blockers:string|null;next_action:string|null;created_at:string}>;
  goal_progress_events?:Array<{id:string;value:number;delta:number;note:string|null;occurred_at:string}>;
  activities?:Array<{id:string;description:string;occurred_at:string;duration_minutes:number|null;effort:string}>;
  goal_tags?:Array<{tag_id:string;tags:{name:string;color:string|null}|null}>;
  goal_relationships?:Array<{id:string;to_goal_id:string;relationship_type:string;goals:{title:string;status:string}|null}>;
  available_goals?:Array<{id:string;title:string;status:string}>;
};

export default function LiveGoalContext({goalId}:{goalId:string}){
  const [data,setData]=useState<GoalContext|null>(null),[failed,setFailed]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const load=useCallback(()=>fetch(`/api/v1/goals/${goalId}`).then(response=>{if(!response.ok)throw new Error();return response.json()}).then(body=>{setData(body.data);setFailed(false)}).catch(()=>setFailed(true)),[goalId]);
  useEffect(()=>{load()},[load]);
  const send=async(url:string,options:RequestInit,success:string)=>{setBusy(true);setMessage("");const response=await fetch(url,options);setBusy(false);if(!response.ok){const body=await response.json().catch(()=>null);setMessage(body?.error?.message||"That change could not be saved.");return false}setMessage(success);await load();return true};
  const addMilestone=async(form:FormData)=>{const title=String(form.get("title")||"");if(await send(`/api/v1/goals/${goalId}/milestones`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title})},"Milestone added.")){(document.getElementById(`milestone-${goalId}`) as HTMLFormElement)?.reset()}};
  const addReview=async(form:FormData)=>{const body={summary:String(form.get("summary")||""),momentum:String(form.get("momentum")||"steady"),blockers:String(form.get("blockers")||""),nextAction:String(form.get("nextAction")||"")};if(await send(`/api/v1/goals/${goalId}/reviews`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)},"Review saved.")){(document.getElementById(`review-${goalId}`) as HTMLFormElement)?.reset()}};
  const organize=async(form:FormData)=>{const tags=String(form.get("tags")||"").split(",").map(tag=>tag.trim()).filter(Boolean),relatedGoalId=String(form.get("relatedGoalId")||""),relationshipType=String(form.get("relationshipType")||"");await send(`/api/v1/goals/${goalId}/organization`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({tags,relatedGoalId:relatedGoalId||undefined,relationshipType:relatedGoalId?relationshipType:undefined})},"Goal organisation saved.")};
  if(failed)return <div className="card side-card"><h3>Goal context</h3><p>Extra goal details could not be loaded. Your saved progress is unaffected.</p><button className="outline" onClick={load}>Try again</button></div>;
  if(!data)return <div className="card side-card" aria-busy="true"><h3>Goal context</h3><p>Loading linked progress…</p></div>;
  const links=data.goal_skill_links||[],milestones=data.goal_milestones||[],reviews=[...(data.goal_reviews||[])].sort((a,b)=>b.created_at.localeCompare(a.created_at)),progress=data.goal_progress_events||[],activities=data.activities||[],tags=data.goal_tags||[],relationships=data.goal_relationships||[],availableGoals=data.available_goals||[];
  return <div className="goal-context-stack">
    {message&&<p className="form-status" role="status">{message}</p>}
    <div className="card side-card"><h3>Plan & milestones</h3>{milestones.length?milestones.map(milestone=><div className="linked" key={milestone.id}><button className="icon-btn" aria-label={`${milestone.completed_at?"Reopen":"Complete"} ${milestone.title}`} disabled={busy} onClick={()=>send(`/api/v1/goals/${goalId}/milestones/${milestone.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({completed:!milestone.completed_at})},milestone.completed_at?"Milestone reopened.":"Milestone completed.")}><Check/></button><div><b>{milestone.title}</b><small>{milestone.completed_at?"Completed":"Next step"}</small></div><button className="icon-btn" aria-label={`Delete ${milestone.title}`} disabled={busy} onClick={()=>send(`/api/v1/goals/${goalId}/milestones/${milestone.id}`,{method:"DELETE"},"Milestone removed.")}><Trash2/></button></div>):<p>Break this goal into the next meaningful checkpoints.</p>}<form id={`milestone-${goalId}`} className="inline-form" action={addMilestone}><label><span className="sr-only">New milestone</span><input name="title" placeholder="Add a milestone" required maxLength={180}/></label><button className="outline" disabled={busy}><Plus/> Add</button></form></div>
    <div className="card side-card"><h3>Linked skills</h3>{links.length?links.map(link=><div className="linked" key={link.skill_id}><span><Sparkles/></span><div><b>{link.skills?.name||"Skill"}</b><small>{link.skills?.category||"Personal"}</small></div><em>{Math.round(link.weight*100)}%</em></div>):<p>No skills linked yet. Link one when logging your next activity.</p>}</div>
    <div className="card side-card"><h3>Organisation</h3>{tags.length>0&&<p>{tags.map(tag=><span className="pill" key={tag.tag_id}>{tag.tags?.name}</span>)}</p>}{relationships.map(relationship=><div className="linked" key={relationship.id}><div><b>{relationship.goals?.title||"Related goal"}</b><small>{relationship.relationship_type} · {relationship.goals?.status}</small></div><button className="icon-btn" aria-label={`Remove relationship with ${relationship.goals?.title||"goal"}`} onClick={()=>send(`/api/v1/goals/${goalId}/organization?relationshipId=${relationship.id}`,{method:"DELETE"},"Relationship removed.")}><Trash2/></button></div>)}<form className="real-form compact-form" action={organize}><label>Tags<input name="tags" defaultValue={tags.map(tag=>tag.tags?.name).filter(Boolean).join(", ")} placeholder="work, 2026, health"/></label><div className="form-row"><label>Relationship<select name="relationshipType" defaultValue="related"><option value="related">Related to</option><option value="dependency">Depends on</option><option value="successor">Succeeds</option><option value="parent">Parent of</option><option value="child">Child of</option></select></label><label>Other goal<select name="relatedGoalId"><option value="">No new relationship</option>{availableGoals.map(goal=><option value={goal.id} key={goal.id}>{goal.title}</option>)}</select></label></div><button className="outline" disabled={busy}><Check/> Save organisation</button></form></div>
    <div className="card side-card"><h3>Recent activity</h3>{activities.length?activities.slice(0,6).map(activity=><p className="timeline-line" key={activity.id}><i/>{activity.description}<small>{new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short"}).format(new Date(activity.occurred_at))}{activity.duration_minutes?` · ${activity.duration_minutes} min`:""}</small></p>):<p>No linked activities yet.</p>}{progress.slice(0,4).map(event=><p className="timeline-line" key={event.id}><i/>Progress changed to {event.value}<small>{event.note||new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short"}).format(new Date(event.occurred_at))}</small></p>)}</div>
    <div className="card side-card"><h3>Weekly review</h3>{reviews[0]?<><p>{reviews[0].summary||"Review saved"}</p><small>Momentum: {reviews[0].momentum||"Not set"}</small>{reviews[0].blockers&&<p><b>Blockers:</b> {reviews[0].blockers}</p>}{reviews[0].next_action&&<p><b>Next:</b> {reviews[0].next_action}</p>}</>:<p>No review yet. A short check-in keeps the goal relevant without erasing its history.</p>}<form id={`review-${goalId}`} className="real-form compact-form" action={addReview}><label>How is it going?<textarea name="summary" required maxLength={1000}/></label><label>Momentum<select name="momentum" defaultValue="steady"><option value="building">Building</option><option value="high">High</option><option value="steady">Steady</option><option value="cooling">Cooling</option><option value="inactive">Inactive</option></select></label><label>What is getting in the way?<input name="blockers" maxLength={500}/></label><label>Next meaningful action<input name="nextAction" maxLength={500}/></label><button className="outline" disabled={busy}><Check/> Save review</button></form></div>
  </div>;
}
