"use client";
import {useEffect,useState} from "react";
import {Activity,Archive,Check,GitMerge,Pencil,Swords,Target,X} from "lucide-react";
import type {Skill} from "@/app/page";

type Detail={name:string;category:string;discovered_at:string;lifetimeXp:number;last30Days:number;sourceTotals:Record<string,number>;activities:Array<{xp_awarded:number;activities:{id:string;description:string;occurred_at:string;duration_minutes:number|null;confidence:string}|null}>;goals:Array<{weight:number;goals:{id:string;title:string;status:string;current_value:number;target_value:number|null;unit:string|null;currency:string|null}|null}>};

export default function LiveSkillDetail({skill,onChanged,notify}:{skill:Skill;onChanged:(skill:Skill|null)=>void;notify:(message:string)=>void}){
 const [detail,setDetail]=useState<Detail|null>(null),[failed,setFailed]=useState(false),[editing,setEditing]=useState(false),[merging,setMerging]=useState(false),[mergeTargets,setMergeTargets]=useState<Array<{id:string;name:string}>>([]);
 const load=()=>fetch(`/api/v1/skills/${skill.id}`).then(response=>{if(!response.ok)throw new Error();return response.json()}).then(body=>{setDetail(body.data);setFailed(false)}).catch(()=>setFailed(true));
 useEffect(()=>{fetch(`/api/v1/skills/${skill.id}`).then(response=>{if(!response.ok)throw new Error();return response.json()}).then(body=>{setDetail(body.data);setFailed(false)}).catch(()=>setFailed(true))},[skill.id]);
 const save=async(form:FormData)=>{const name=String(form.get("name")||""),category=String(form.get("category")||"");const response=await fetch(`/api/v1/skills/${skill.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({name,category})});if(!response.ok)return notify("Skill changes could not be saved.");onChanged({...skill,name,category});setEditing(false);load();notify("Skill updated")};
 const archive=async()=>{if(!confirm("Archive this skill? Its XP and history will remain."))return;const response=await fetch(`/api/v1/skills/${skill.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({archived:true})});if(!response.ok)return notify("Skill could not be archived.");onChanged(null);notify("Skill archived. Its history and XP remain.")};
 const openMerge=async()=>{const response=await fetch("/api/v1/skills"),body=await response.json();setMergeTargets((body.data||[]).filter((item:{id:string})=>item.id!==skill.id));setMerging(true)};
 const merge=async(form:FormData)=>{if(!detail)return;const retainedSkillId=String(form.get("retainedSkillId")||""),retained=mergeTargets.find(item=>item.id===retainedSkillId);if(!retainedSkillId||!confirm(`Merge ${detail.name} into ${retained?.name||"the retained skill"}? The original branch will be archived and its XP audit history preserved.`))return;const response=await fetch("/api/v1/skills/merge",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({sourceSkillId:skill.id,retainedSkillId})});if(!response.ok){const body=await response.json().catch(()=>null);return notify(body?.error?.message||"Skills could not be merged.")}setMerging(false);onChanged(null);notify(`Skills merged into ${retained?.name||"the retained branch"}. XP was preserved.`)};
 if(failed)return <div className="empty"><h2>Skill details could not be loaded</h2><p>Your saved XP is unaffected.</p><button className="outline" onClick={load}>Try again</button></div>;
 if(!detail)return <div className="empty" aria-busy="true"><h2>Loading skill history…</h2></div>;
 const sourceEntries=Object.entries(detail.sourceTotals).sort((a,b)=>b[1]-a[1]);
 return <>
  <div className="skill-hero" style={{"--accent":skill.color} as React.CSSProperties}><div className="skill-badge">{skill.icon}</div><div><p>{detail.category}</p><h2>{detail.name}</h2><span>Discovered {new Intl.DateTimeFormat("en-GB",{month:"long",year:"numeric"}).format(new Date(detail.discovered_at))}</span></div><div className="level-block"><small>CURRENT LEVEL</small><b>{skill.level}</b></div><button className="outline" onClick={()=>setEditing(true)}><Pencil/> Edit</button><button className="outline" onClick={openMerge}><GitMerge/> Merge</button><button className="outline" onClick={archive}><Archive/> Archive</button></div>
  <div className="stats-row"><div><b>{detail.lifetimeXp.toLocaleString()}</b><small>Lifetime XP</small></div><div><b>{detail.last30Days>=0?"+":""}{detail.last30Days.toLocaleString()}</b><small>Last 30 days</small></div><div><b>{detail.activities.length}</b><small>Recent activities</small></div><div><b>{detail.goals.length}</b><small>Related goals</small></div></div>
  <div className="detail-grid"><div><div className="card side-card"><h3>How you gained XP</h3>{sourceEntries.length?sourceEntries.map(([source,amount])=><div className="linked" key={source}><span>{source==="quest"?<Swords/>:<Activity/>}</span><div><b>{source.replaceAll("_"," ")}</b><small>Recent ledger activity</small></div><em>{amount>=0?"+":""}{amount} XP</em></div>):<p>Log meaningful work and link it to this skill to begin its history.</p>}</div><div className="card side-card"><h3>Recent activity</h3>{detail.activities.length?detail.activities.slice(0,10).map(link=>link.activities&&<p className="timeline-line" key={link.activities.id}><i/>{link.activities.description}<small>{new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short"}).format(new Date(link.activities.occurred_at))} · +{link.xp_awarded} XP</small></p>):<p>No linked activities yet.</p>}</div></div><div><div className="card side-card"><h3>Related goals</h3>{detail.goals.length?detail.goals.map(link=>link.goals&&<div className="linked" key={link.goals.id}><span><Target/></span><div><b>{link.goals.title}</b><small>{link.goals.status} · {link.goals.target_value?Math.round(Number(link.goals.current_value)/Number(link.goals.target_value)*100):0}%</small></div><em>{Math.round(link.weight*100)}%</em></div>):<p>This skill is independent of your current goals.</p>}</div><div className="card side-card"><h3>Persistence</h3><p>Skill XP remains part of your character even when related goals are paused, completed, or abandoned.</p></div></div></div>
  {editing&&<Modal title="Edit skill" close={()=>setEditing(false)}><form className="real-form" action={save}><label>Name<input name="name" defaultValue={detail.name} required maxLength={100}/></label><label>Category<input name="category" defaultValue={detail.category} required/></label><div className="form-actions"><button type="button" className="outline" onClick={()=>setEditing(false)}>Cancel</button><button className="primary"><Check/> Save changes</button></div></form></Modal>}
  {merging&&<Modal title={`Merge ${detail.name}`} close={()=>setMerging(false)}><p>Choose the branch to keep. Activities, links, and the complete XP audit trail remain intact.</p><form className="real-form" action={merge}><label>Retained skill<select name="retainedSkillId" required><option value="">Choose a skill</option>{mergeTargets.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div className="form-actions"><button type="button" className="outline" onClick={()=>setMerging(false)}>Cancel</button><button className="primary" disabled={!mergeTargets.length}><GitMerge/> Merge skills</button></div></form></Modal>}
 </>;
}

function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="modal-wrap"><div className="quick-modal" role="dialog" aria-modal="true" aria-label={title}><div className="modal-head"><h2>{title}</h2><button className="icon-btn" aria-label={`Close ${title}`} onClick={close}><X/></button></div>{children}</div></div>}
