/* eslint-disable react-hooks/set-state-in-effect */
"use client";import {useEffect,useMemo,useState} from "react";import {Bell,CalendarDays,Check,Trash2} from "lucide-react";
type CalendarData={from:string;to:string;quests:Array<{id:string;title:string;due_at:string;status:string}>;goals:Array<{id:string;title:string;deadline:string;status:string}>;habits:Array<{id:string;name:string;start_date:string;end_date:string|null;frequency:unknown}>;focusSessions:Array<{id:string;started_at:string;planned_minutes:number;status:string}>};
type Reminder={id:string;title:string;reminder_type:string;enabled:boolean;next_run_at:string|null;timezone:string};
export default function LiveCalendar(){
 const [data,setData]=useState<CalendarData|null>(null),[reminders,setReminders]=useState<Reminder[]>([]),[message,setMessage]=useState(""),[loading,setLoading]=useState(true),[offset,setOffset]=useState(0);
 const range=useMemo(()=>{const from=new Date();from.setDate(from.getDate()+offset*31);const to=new Date(from);to.setDate(to.getDate()+30);return{from:from.toISOString().slice(0,10),to:to.toISOString().slice(0,10)}},[offset]);
 const load=()=>Promise.all([fetch(`/api/v1/calendar?from=${range.from}&to=${range.to}`).then(r=>r.json()),fetch("/api/v1/reminders").then(r=>r.json())]).then(([calendar,reminderBody])=>{setData(calendar.data);setReminders(reminderBody.data||[]);setLoading(false)});
 useEffect(()=>{setLoading(true);Promise.all([fetch(`/api/v1/calendar?from=${range.from}&to=${range.to}`).then(r=>r.json()),fetch("/api/v1/reminders").then(r=>r.json())]).then(([calendar,reminderBody])=>{setData(calendar.data);setReminders(reminderBody.data||[]);setLoading(false)})},[range]);
 const addReminder=async(form:FormData)=>{const nextRunAt=new Date(String(form.get("nextRunAt"))).toISOString(),response=await fetch("/api/v1/reminders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title:form.get("title"),type:"custom",timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,nextRunAt,schedule:{kind:"once",at:nextRunAt}})});setMessage(response.ok?"Reminder scheduled.":"Reminder could not be scheduled.");if(response.ok)load()};
 const toggle=async(reminder:Reminder)=>{await fetch(`/api/v1/reminders/${reminder.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({enabled:!reminder.enabled})});load()};
 const remove=async(id:string)=>{if(!confirm("Delete this reminder?"))return;await fetch(`/api/v1/reminders/${id}`,{method:"DELETE"});load()};
 const events=[...(data?.quests||[]).map(item=>({id:item.id,date:item.due_at,title:item.title,type:"Quest",status:item.status})),...(data?.goals||[]).map(item=>({id:item.id,date:item.deadline,title:item.title,type:"Goal deadline",status:item.status})),...(data?.focusSessions||[]).map(item=>({id:item.id,date:item.started_at,title:`${item.planned_minutes}-minute focus session`,type:"Focus",status:item.status}))].sort((a,b)=>a.date.localeCompare(b.date));
 if(loading)return <div className="live-loading"><i/><i/><i/></div>;
 return <>{message&&<p className="modal-tip" role="status">{message}</p>}<div className="toolbar"><div><h2>Calendar</h2><p>{new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"long"}).format(new Date(`${range.from}T12:00:00`))} – {new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"long",year:"numeric"}).format(new Date(`${range.to}T12:00:00`))}</p></div><div className="form-actions"><button className="outline" onClick={()=>setOffset(value=>value-1)}>Previous</button><button className="outline" onClick={()=>setOffset(0)}>Today</button><button className="outline" onClick={()=>setOffset(value=>value+1)}>Next</button></div></div><div className="detail-grid"><div className="card side-card"><h3>Scheduled progress</h3>{events.length?events.map(event=><div className="linked" key={`${event.type}-${event.id}`}><span><CalendarDays/></span><div><b>{event.title}</b><small>{event.type} · {new Intl.DateTimeFormat("en-GB",{weekday:"short",day:"numeric",month:"short"}).format(new Date(event.date))}</small></div><em>{event.status}</em></div>):<p>No deadlines, quests, or focus sessions in this period. Goals without deadlines remain completely valid.</p>}<h3>Recurring habits</h3>{(data?.habits||[]).map(habit=><p key={habit.id}><b>{habit.name}</b><br/><small>Active from {new Intl.DateTimeFormat("en-GB").format(new Date(`${habit.start_date}T12:00:00`))}</small></p>)}</div><div><form className="card side-card real-form" action={addReminder}><h3><Bell/> New reminder</h3><label>Title<input name="title" required maxLength={180}/></label><label>When<input name="nextRunAt" type="datetime-local" required/></label><button className="primary">Schedule reminder</button></form><div className="card side-card"><h3>Your reminders</h3>{reminders.length?reminders.map(reminder=><div className="linked" key={reminder.id}><button className="icon-btn" aria-label={`${reminder.enabled?"Disable":"Enable"} ${reminder.title}`} onClick={()=>toggle(reminder)}>{reminder.enabled?<Check/>:<Bell/>}</button><div><b>{reminder.title}</b><small>{reminder.enabled?"Enabled":"Paused"}{reminder.next_run_at?` · ${new Date(reminder.next_run_at).toLocaleString()}`:""}</small></div><button className="icon-btn" aria-label={`Delete ${reminder.title}`} onClick={()=>remove(reminder.id)}><Trash2/></button></div>):<p>No reminders. SkillTree never punishes missed days.</p>}</div></div></div></>;
}
