/* eslint-disable react-hooks/set-state-in-effect */
"use client";import {useEffect,useMemo,useState} from "react";import {Award,BarChart3,Clock3,Flame,RotateCcw,Search,Sparkles,Target,Zap} from "lucide-react";
function Loading(){return <div className="live-loading"><i/><i/><i/></div>}
function ErrorState({retry}:{retry:()=>void}){return <div className="empty"><div><Sparkles/></div><h2>That page did not load</h2><p>Your data is safe. Check your connection and try again.</p><button className="primary" onClick={retry}>Retry</button></div>}
type HistoryEvent={id:string;type:string;title:string;occurredAt:string;xp?:number;undo?:{type:string;id:string}};
export function LiveHistory({locale="en-GB"}:{locale?:string}){
 const [events,setEvents]=useState<HistoryEvent[]>([]),[loading,setLoading]=useState(true),[loadingMore,setLoadingMore]=useState(false),[failed,setFailed]=useState(false),[nonce,setNonce]=useState(0),[query,setQuery]=useState(""),[filter,setFilter]=useState("all"),[message,setMessage]=useState(""),[nextCursor,setNextCursor]=useState<string|null>(null);
 useEffect(()=>{setLoading(true);fetch("/api/v1/history").then(r=>{if(!r.ok)throw new Error();return r.json()}).then(b=>{setEvents(b.data||[]);setNextCursor(b.nextCursor||null);setFailed(false)}).catch(()=>setFailed(true)).finally(()=>setLoading(false))},[nonce]);
 const visible=useMemo(()=>events.filter(event=>(filter==="all"||event.type===filter)&&event.title.toLowerCase().includes(query.toLowerCase())),[events,filter,query]);
 const undo=async(event:HistoryEvent)=>{if(!event.undo||!confirm(`Undo “${event.title}”? Audit history will be preserved.`))return;const response=await fetch("/api/v1/undo",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(event.undo)}),body=await response.json().catch(()=>null);setMessage(response.ok?"Action undone. A correction was added to history.":body?.error?.message||"That action could not be undone.");if(response.ok)setNonce(n=>n+1)};
 const loadMore=async()=>{if(!nextCursor||loadingMore)return;setLoadingMore(true);setMessage("");try{const response=await fetch(`/api/v1/history?cursor=${encodeURIComponent(nextCursor)}`);if(!response.ok)throw new Error();const body=await response.json(),incoming=(body.data||[]) as HistoryEvent[];setEvents(current=>{const known=new Set(current.map(event=>`${event.type}:${event.id}`));return[...current,...incoming.filter(event=>!known.has(`${event.type}:${event.id}`))]});setNextCursor(body.nextCursor||null)}catch{setMessage("Older history could not be loaded. Try again.")}finally{setLoadingMore(false)}};
 if(loading)return <Loading/>;if(failed)return <ErrorState retry={()=>setNonce(n=>n+1)}/>;
 return <>
  {message&&<p className="modal-tip" role="status">{message}</p>}
  <div className="filterbar"><div className="search"><Search/><input aria-label="Search history" placeholder="Search loaded history" value={query} onChange={event=>setQuery(event.target.value)}/></div><label>Type<select value={filter} onChange={event=>setFilter(event.target.value)}><option value="all">All activity</option><option value="activity">Activities</option><option value="quest_completion">Quests</option><option value="goal_progress">Goal progress</option><option value="goal_revision">Goal changes</option><option value="achievement">Achievements</option><option value="correction">Corrections</option></select></label></div>
  {visible.length===0?<div className="empty"><div><Clock3/></div><h2>{events.length?"No loaded history matches that filter":"Your progress history starts here"}</h2><p>Activities, goal changes, achievements and corrections remain part of your character story.</p></div>:<div className="history-list">{visible.map(event=><div className="history-row" key={`${event.type}-${event.id}`}><span className="history-date">{new Intl.DateTimeFormat(locale,{day:"numeric",month:"short"}).format(new Date(event.occurredAt))}</span><i style={{background:event.type==="achievement"?"#ca9d42":event.type==="goal_progress"?"#44a77a":"#7c6cf2"}}/><div><small>{event.type.replaceAll("_"," ")}</small><h3>{event.title}</h3></div>{event.xp?<b>+{event.xp} XP</b>:null}{event.undo&&<button className="outline" onClick={()=>undo(event)}><RotateCcw/> Undo</button>}</div>)}</div>}
  {nextCursor&&<button className="load" disabled={loadingMore} onClick={loadMore}>{loadingMore?"Loading older history…":"Load older history"}</button>}
 </>;
}
type Achievement={key:string;title:string;description:string;category:string;unlock:null|{unlocked_at:string}};
export function LiveAchievements(){const [items,setItems]=useState<Achievement[]>([]),[loading,setLoading]=useState(true),[failed,setFailed]=useState(false),[nonce,setNonce]=useState(0);useEffect(()=>{fetch("/api/v1/achievements").then(r=>{if(!r.ok)throw new Error();return r.json()}).then(b=>{setItems(b.data||[]);setFailed(false)}).catch(()=>setFailed(true)).finally(()=>setLoading(false))},[nonce]);if(loading)return <Loading/>;if(failed)return <ErrorState retry={()=>{setLoading(true);setNonce(n=>n+1)}}/>;const unlocked=items.filter(x=>x.unlock);return <><div className="achievement-hero"><div><span className="eyebrow">ACHIEVEMENT SHOWCASE</span><h2>{unlocked[0]?.title||"Your first achievement awaits"}</h2><p>{unlocked[0]?.description||"Meaningful moments in your progress will be remembered here."}</p><span className="rarity">Achievements never disappear when your goals change.</span></div><div className="medal">{unlocked.length?"◆":"?"}</div></div><div className="section-head"><h2>Your achievements</h2><span>{unlocked.length} unlocked</span></div><div className="achievement-grid">{items.map(item=><a href={`/achievements/${encodeURIComponent(item.key)}`} className={item.unlock?"achievement":"achievement locked-achievement"} key={item.key}><span>{item.unlock?<Award/>:"?"}</span><div><h3>{item.title}</h3><p>{item.description}</p><small>{item.unlock?`Unlocked ${new Intl.DateTimeFormat("en-GB").format(new Date(item.unlock.unlocked_at))}`:"Locked"}</small></div></a>)}</div></>}
type Insight={lifetime_xp:number;weekly_xp:number;activeDays30:number;goalsMoved30:number;activities14:number;level:number;strongestSkills:Array<{skill_id:string;name:string;category:string;recent_xp:number}>;forecasts:Array<{goalId:string;title:string;range:string;explanation:string}>;daily:{activities:number;xp:number;quests:number;habits:number;goals:number};weekly:{xp:number;strongestSkill:string|null;goals:number;activeDays:number;nextFocus:string|null}};
export function LiveInsights(){const [data,setData]=useState<Insight|null>(null),[loading,setLoading]=useState(true),[failed,setFailed]=useState(false),[nonce,setNonce]=useState(0);useEffect(()=>{fetch("/api/v1/insights").then(r=>{if(!r.ok)throw new Error();return r.json()}).then(b=>{setData(b.data);setFailed(false)}).catch(()=>setFailed(true)).finally(()=>setLoading(false))},[nonce]);if(loading)return <Loading/>;if(failed||!data)return <ErrorState retry={()=>{setLoading(true);setNonce(n=>n+1)}}/>;return <><div className="insight-top"><div className="card score"><span className="eyebrow">THIS WEEK</span><b>{Number(data.weekly.xp).toLocaleString()}</b><small>XP earned</small><em>Level {data.level} overall</em></div><div className="card score"><span className="eyebrow">ACTIVE DAYS</span><b>{data.activeDays30}</b><small>of the last 30 days</small><em>{data.activities14} activities in 14 days</em></div><div className="card score"><span className="eyebrow">GOALS MOVED</span><b>{data.goalsMoved30}</b><small>in the last 30 days</small><em>{data.goalsMoved30?"Progress is moving":"Choose one useful next action"}</em></div></div><div className="detail-grid"><div><div className="card chart-card"><div className="section-head"><h2>Today’s summary</h2><span>No guilt, just signal</span></div><div className="live-character"><div><Zap/><b>{data.daily.xp}</b><small>XP</small></div><div><Target/><b>{data.daily.activities}</b><small>Activities</small></div><div><Award/><b>{data.daily.quests}</b><small>Quests</small></div><div><Flame/><b>{data.daily.habits}</b><small>Habits</small></div></div></div><div className="card side-card"><h3>Completion forecasts</h3>{data.forecasts.length?data.forecasts.map(forecast=><div className="linked" key={forecast.goalId}><div><b>{forecast.title}</b><small>At your observed pace: {forecast.range}</small><p>{forecast.explanation}</p></div></div>):<p>Forecasts appear after at least three positive progress updates. SkillTree shows a range rather than false precision.</p>}</div></div><div><div className="card side-card"><h3>Weekly summary</h3><p><b>{data.weekly.xp} XP</b> across {data.weekly.activeDays} active days.</p><p>{data.weekly.goals} goals moved{data.weekly.strongestSkill?`, led by ${data.weekly.strongestSkill}`:""}.</p><p>Next focus: {data.weekly.nextFocus||"choose one useful action"}.</p></div><div className="card side-card"><h3>Strongest recent skills</h3>{data.strongestSkills.map((skill,index)=><div className="rank" key={skill.skill_id}><b>{index+1}</b><span><BarChart3/></span><div><strong>{skill.name}</strong><small>+{skill.recent_xp} XP</small></div></div>)}</div><div className="card insight-note"><Sparkles/><div><b>A useful pattern</b><p>{data.activities14?"Keep choosing progress you can sustain.":"Start small. One meaningful action is enough to restart momentum."}</p></div></div></div></div></>}
