create table public.seasons (id uuid primary key default gen_random_uuid(), name text not null, starts_at timestamptz not null, ends_at timestamptz not null, is_active boolean not null default false, metadata jsonb not null default '{}', check(ends_at>starts_at));
create unique index one_active_season on public.seasons(is_active) where is_active;
create table public.season_user_stats (season_id uuid not null references public.seasons(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, xp_earned bigint not null default 0, activities integer not null default 0, quests_completed integer not null default 0, habits_completed integer not null default 0, updated_at timestamptz not null default now(), primary key(season_id,user_id));
alter table public.seasons enable row level security; alter table public.season_user_stats enable row level security;
create policy seasons_read on public.seasons for select to authenticated using(true); create policy season_stats_read on public.season_user_stats for select to authenticated using((select auth.uid())=user_id);
grant select on public.seasons,public.season_user_stats to authenticated;

create view public.skill_xp_totals with(security_invoker=true) as select s.id skill_id,s.user_id,s.name,s.category,s.parent_id,s.discovered_at,coalesce(x.lifetime_xp,0)::bigint lifetime_xp,coalesce(x.recent_xp,0)::bigint recent_xp,coalesce(a.lifetime_activities,0)::integer lifetime_activities from public.skills s left join lateral(select sum(amount) lifetime_xp,sum(amount) filter(where created_at>now()-interval '30 days') recent_xp from public.xp_transactions where skill_id=s.id)x on true left join lateral(select count(distinct activity_id) lifetime_activities from public.activity_skill_links where skill_id=s.id)a on true where s.archived_at is null;
create view public.user_progress_summary with(security_invoker=true) as select p.id user_id,coalesce(x.lifetime_xp,0)::bigint lifetime_xp,coalesce(x.weekly_xp,0)::bigint weekly_xp,coalesce(x.discovered_skills,0)::integer discovered_skills,coalesce(a.lifetime_activities,0)::integer lifetime_activities from public.profiles p left join lateral(select sum(amount) lifetime_xp,sum(amount) filter(where created_at>now()-interval '7 days') weekly_xp,count(distinct skill_id) discovered_skills from public.xp_transactions where user_id=p.id)x on true left join lateral(select count(*) lifetime_activities from public.activities where user_id=p.id)a on true;
grant select on public.skill_xp_totals,public.user_progress_summary to authenticated;

insert into public.achievement_definitions(key,title,description,category,rarity_eligible,xp_reward,criteria) values
('first_activity','First Steps','Log your first activity','system',true,0,'{"activityCount":1}'),
('ten_activities','Finding Momentum','Log ten meaningful activities','system',true,0,'{"activityCount":10}'),
('hundred_activities','Century','Log one hundred meaningful activities','system',true,0,'{"activityCount":100}'),
('first_goal','A Direction Chosen','Create your first goal','system',true,0,'{"goalCount":1}'),
('first_completed_goal','Goal Getter','Complete your first goal','system',true,0,'{"completedGoalCount":1}') on conflict(key) do nothing;

create or replace function public.evaluate_achievements() returns trigger language plpgsql security invoker set search_path='' as $$ declare activity_count integer; goal_count integer; completed_count integer; begin select count(*) into activity_count from public.activities where user_id=new.user_id; select count(*) into goal_count from public.goals where user_id=new.user_id; select count(*) into completed_count from public.goals where user_id=new.user_id and status='completed'; if activity_count>=1 then insert into public.achievement_unlocks(user_id,achievement_key) values(new.user_id,'first_activity') on conflict do nothing; end if; if activity_count>=10 then insert into public.achievement_unlocks(user_id,achievement_key) values(new.user_id,'ten_activities') on conflict do nothing; end if; if activity_count>=100 then insert into public.achievement_unlocks(user_id,achievement_key) values(new.user_id,'hundred_activities') on conflict do nothing; end if; if goal_count>=1 then insert into public.achievement_unlocks(user_id,achievement_key) values(new.user_id,'first_goal') on conflict do nothing; end if; if completed_count>=1 then insert into public.achievement_unlocks(user_id,achievement_key) values(new.user_id,'first_completed_goal') on conflict do nothing; end if; return new; end $$;
create trigger evaluate_after_activity after insert on public.activities for each row execute function public.evaluate_achievements();
create trigger evaluate_after_goal after insert or update of status on public.goals for each row execute function public.evaluate_achievements();

create or replace function public.refresh_season_stats(p_user_id uuid) returns void language plpgsql security invoker set search_path='' as $$ declare active public.seasons; begin if p_user_id<>(select auth.uid()) then raise exception 'FORBIDDEN'; end if; select * into active from public.seasons where is_active limit 1; if not found then return; end if; insert into public.season_user_stats(season_id,user_id,xp_earned,activities,quests_completed,habits_completed) select active.id,p_user_id,coalesce((select sum(amount) from public.xp_transactions where user_id=p_user_id and created_at between active.starts_at and active.ends_at),0),coalesce((select count(*) from public.activities where user_id=p_user_id and occurred_at between active.starts_at and active.ends_at),0),coalesce((select count(*) from public.quest_completions where user_id=p_user_id and completed_at between active.starts_at and active.ends_at),0),coalesce((select count(*) from public.habit_occurrences where user_id=p_user_id and status='complete' and created_at between active.starts_at and active.ends_at),0) on conflict(season_id,user_id) do update set xp_earned=excluded.xp_earned,activities=excluded.activities,quests_completed=excluded.quests_completed,habits_completed=excluded.habits_completed,updated_at=now(); end $$;
revoke all on function public.refresh_season_stats(uuid) from public,anon;grant execute on function public.refresh_season_stats(uuid) to authenticated;

insert into public.seasons(name,starts_at,ends_at,is_active) select 'Season 3',date_trunc('quarter',now()),date_trunc('quarter',now())+interval '3 months',true where not exists(select 1 from public.seasons where is_active);
