alter table public.profiles add column public_slug text unique,add column visibility text not null default 'private' check(visibility in('private','unlisted','public')),add column bio text,add column accent text not null default '#7465e8',add column featured_achievement_keys text[] not null default '{}';
create policy profiles_shared_read on public.profiles for select to anon,authenticated using(visibility in('public','unlisted'));
create table public.public_profile_snapshots(user_id uuid primary key references auth.users(id) on delete cascade,summary jsonb not null default '{}',skills jsonb not null default '[]',focus_goals jsonb not null default '[]',achievements jsonb not null default '[]',updated_at timestamptz not null default now());
alter table public.public_profile_snapshots enable row level security;create policy public_snapshots_owner_write on public.public_profile_snapshots for all to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));create policy public_snapshots_shared_read on public.public_profile_snapshots for select to anon,authenticated using(exists(select 1 from public.profiles p where p.id=user_id and p.visibility in('public','unlisted')));grant select on public.public_profile_snapshots to anon,authenticated;grant insert,update,delete on public.public_profile_snapshots to authenticated;
create table public.friendships (id uuid primary key default gen_random_uuid(), requester_id uuid not null references auth.users(id) on delete cascade, addressee_id uuid not null references auth.users(id) on delete cascade, status text not null default 'pending' check(status in('pending','accepted','declined','blocked')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check(requester_id<>addressee_id),unique(requester_id,addressee_id));
create table public.challenges (id uuid primary key default gen_random_uuid(), creator_id uuid not null references auth.users(id) on delete cascade, title text not null, description text, starts_at timestamptz not null, ends_at timestamptz not null, metric text not null check(metric in('activities','xp','distance','duration','custom')), target numeric, visibility text not null default 'invite_only' check(visibility in('invite_only','friends','public')), created_at timestamptz not null default now(),check(ends_at>starts_at));
create table public.challenge_members (challenge_id uuid not null references public.challenges(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,status text not null default 'invited' check(status in('invited','accepted','declined','left')),progress numeric not null default 0,joined_at timestamptz,primary key(challenge_id,user_id));
create table public.integrations (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,provider text not null,status text not null default 'connected' check(status in('connected','degraded','disconnected','revoked')),scopes text[] not null default '{}',external_account_id text,last_synced_at timestamptz,error_code text,metadata jsonb not null default '{}',created_at timestamptz not null default now(),unique(user_id,provider,external_account_id));
create table public.integration_events (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,integration_id uuid not null references public.integrations(id) on delete cascade,external_id text not null,event_type text not null,payload jsonb not null,processed_at timestamptz,error_code text,created_at timestamptz not null default now(),unique(integration_id,external_id));
create table public.imports (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,source text not null,status text not null default 'uploaded' check(status in('uploaded','mapping','processing','completed','failed','cancelled')),filename text,total_rows integer not null default 0,processed_rows integer not null default 0,error_rows integer not null default 0,mapping jsonb,created_at timestamptz not null default now(),completed_at timestamptz);
create table public.import_rows (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,import_id uuid not null references public.imports(id) on delete cascade,row_number integer not null,raw_data jsonb not null,status text not null default 'pending' check(status in('pending','processed','skipped','error')),result_id uuid,error_message text,unique(import_id,row_number));
create table public.subscriptions (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,provider text not null default 'stripe',provider_customer_id text unique,provider_subscription_id text unique,plan text not null default 'free' check(plan in('free','pro','lifetime')),status text not null default 'active' check(status in('trialing','active','past_due','cancelled','expired')),current_period_end timestamptz,cancel_at_period_end boolean not null default false,updated_at timestamptz not null default now(),unique(user_id));
create table public.entitlements (user_id uuid not null references auth.users(id) on delete cascade,entitlement text not null,source text not null,expires_at timestamptz,created_at timestamptz not null default now(),primary key(user_id,entitlement));
create table public.referrals (id uuid primary key default gen_random_uuid(),referrer_id uuid not null references auth.users(id) on delete cascade,referred_id uuid references auth.users(id) on delete set null,code text not null unique,status text not null default 'clicked' check(status in('clicked','signed_up','converted')),created_at timestamptz not null default now(),converted_at timestamptz);

alter table public.friendships enable row level security;alter table public.challenges enable row level security;alter table public.challenge_members enable row level security;
do $$ declare t text;begin foreach t in array array['integrations','integration_events','imports','import_rows','subscriptions','entitlements'] loop execute format('alter table public.%I enable row level security',t);execute format('create policy %I on public.%I for select to authenticated using((select auth.uid())=user_id)',t||'_select',t);end loop;end $$;
alter table public.referrals enable row level security;
create policy friendships_read on public.friendships for select to authenticated using((select auth.uid()) in(requester_id,addressee_id));create policy friendships_insert on public.friendships for insert to authenticated with check((select auth.uid())=requester_id);create policy friendships_update on public.friendships for update to authenticated using((select auth.uid()) in(requester_id,addressee_id)) with check((select auth.uid()) in(requester_id,addressee_id));
create policy challenges_read on public.challenges for select to authenticated using(creator_id=(select auth.uid()) or visibility='public' or exists(select 1 from public.challenge_members m where m.challenge_id=id and m.user_id=(select auth.uid())));create policy challenges_write on public.challenges for all to authenticated using(creator_id=(select auth.uid())) with check(creator_id=(select auth.uid()));
create policy challenge_members_read on public.challenge_members for select to authenticated using(user_id=(select auth.uid()) or exists(select 1 from public.challenges c where c.id=challenge_id and c.creator_id=(select auth.uid())));create policy challenge_members_update on public.challenge_members for update to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));create policy challenge_members_insert on public.challenge_members for insert to authenticated with check(exists(select 1 from public.challenges c where c.id=challenge_id and c.creator_id=(select auth.uid())));
create policy referrals_read on public.referrals for select to authenticated using(referrer_id=(select auth.uid()) or referred_id=(select auth.uid()));create policy referrals_insert on public.referrals for insert to authenticated with check(referrer_id=(select auth.uid()));
grant select,insert,update,delete on public.friendships,public.challenges,public.challenge_members,public.referrals to authenticated;grant select on public.integrations,public.integration_events,public.imports,public.import_rows,public.subscriptions,public.entitlements to authenticated;
create index friendship_addressee_status_idx on public.friendships(addressee_id,status);create index challenges_visibility_time_idx on public.challenges(visibility,starts_at);create index challenge_members_user_idx on public.challenge_members(user_id,status);create index integration_events_pending_idx on public.integration_events(integration_id,created_at) where processed_at is null;create index import_rows_pending_idx on public.import_rows(import_id,row_number) where status='pending';create index entitlement_user_expiry_idx on public.entitlements(user_id,expires_at);

create or replace function public.accept_friendship(p_friendship_id uuid) returns void language plpgsql security invoker set search_path='' as $$ begin update public.friendships set status='accepted',updated_at=now() where id=p_friendship_id and addressee_id=(select auth.uid()) and status='pending';if not found then raise exception 'FRIENDSHIP_NOT_FOUND';end if;end $$;
create or replace function public.has_entitlement(p_entitlement text) returns boolean language sql stable security invoker set search_path='' as $$ select exists(select 1 from public.entitlements where user_id=(select auth.uid()) and entitlement=p_entitlement and(expires_at is null or expires_at>now())) $$;
create or replace function public.refresh_public_profile() returns void language plpgsql security invoker set search_path='' as $$ begin insert into public.public_profile_snapshots(user_id,summary,skills,focus_goals,achievements,updated_at) values((select auth.uid()),(select jsonb_build_object('lifetimeXp',coalesce(lifetime_xp,0),'discoveredSkills',coalesce(discovered_skills,0),'lifetimeActivities',coalesce(lifetime_activities,0)) from public.user_progress_summary where user_id=(select auth.uid())),coalesce((select jsonb_agg(to_jsonb(s)) from(select name,category,lifetime_xp from public.skill_xp_totals where user_id=(select auth.uid()) order by lifetime_xp desc limit 6)s),'[]'),coalesce((select jsonb_agg(to_jsonb(g)) from(select title,category,current_value "currentValue",target_value "targetValue",unit from public.goals where user_id=(select auth.uid()) and status='focus' order by updated_at desc limit 3)g),'[]'),coalesce((select jsonb_agg(jsonb_build_object('key',au.achievement_key,'unlockedAt',au.unlocked_at)) from public.achievement_unlocks au join public.profiles p on p.id=au.user_id where au.user_id=(select auth.uid()) and au.achievement_key=any(p.featured_achievement_keys)),'[]'),now()) on conflict(user_id) do update set summary=excluded.summary,skills=excluded.skills,focus_goals=excluded.focus_goals,achievements=excluded.achievements,updated_at=now();end $$;
revoke all on function public.accept_friendship(uuid),public.has_entitlement(text),public.refresh_public_profile() from public,anon;grant execute on function public.accept_friendship(uuid),public.has_entitlement(text),public.refresh_public_profile() to authenticated;
