create schema if not exists private;revoke all on schema private from public,anon,authenticated;
create table private.integration_credentials(integration_id uuid primary key references public.integrations(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,access_token_ciphertext text not null,refresh_token_ciphertext text,expires_at timestamptz,updated_at timestamptz not null default now());
create table public.oauth_states(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,provider text not null,state_hash text not null unique,code_verifier_ciphertext text,redirect_to text,expires_at timestamptz not null,used_at timestamptz,created_at timestamptz not null default now());
alter table public.oauth_states enable row level security;revoke all on public.oauth_states from anon,authenticated;
create table public.admin_users(user_id uuid primary key references auth.users(id) on delete cascade,role text not null check(role in('support','moderator','admin')),created_at timestamptz not null default now());
create table public.moderation_flags(id uuid primary key default gen_random_uuid(),reporter_id uuid references auth.users(id) on delete set null,object_type text not null,object_id uuid not null,reason text not null,status text not null default 'open' check(status in('open','reviewing','resolved','dismissed')),assigned_to uuid references auth.users(id) on delete set null,resolution text,created_at timestamptz not null default now(),resolved_at timestamptz);
alter table public.admin_users enable row level security;alter table public.moderation_flags enable row level security;revoke all on public.admin_users,public.moderation_flags from anon,authenticated;

create or replace function private.process_import_batch(p_import_id uuid,p_batch_size integer default 100) returns integer language plpgsql security definer set search_path='' as $$ declare imp public.imports;row_record public.import_rows;created_id uuid;processed integer=0;description text;occurred timestamptz;begin select * into imp from public.imports where id=p_import_id for update;if not found then raise exception 'IMPORT_NOT_FOUND';end if;if imp.status in('completed','cancelled') then return 0;end if;update public.imports set status='processing' where id=imp.id;for row_record in select * from public.import_rows where import_id=imp.id and status='pending' order by row_number for update skip locked limit greatest(1,least(p_batch_size,500)) loop begin description=coalesce(nullif(trim(row_record.raw_data->>'description'),''),'Imported activity');occurred=coalesce((row_record.raw_data->>'occurredAt')::timestamptz,now());insert into public.activities(user_id,description,duration_minutes,quantity,unit,effort,confidence,occurred_at,idempotency_key) values(imp.user_id,description,nullif(row_record.raw_data->>'durationMinutes','')::integer,nullif(row_record.raw_data->>'quantity','')::numeric,row_record.raw_data->>'unit',coalesce(row_record.raw_data->>'effort','moderate'),'self_reported',occurred,'import:'||imp.id||':'||row_record.row_number) on conflict(user_id,idempotency_key) do update set description=excluded.description returning id into created_id;update public.import_rows set status='processed',result_id=created_id where id=row_record.id;processed=processed+1;exception when others then update public.import_rows set status='error',error_message=left(sqlerrm,500) where id=row_record.id;end;end loop;update public.imports set processed_rows=(select count(*) from public.import_rows where import_id=imp.id and status='processed'),error_rows=(select count(*) from public.import_rows where import_id=imp.id and status='error'),status=case when not exists(select 1 from public.import_rows where import_id=imp.id and status='pending') then 'completed' else 'processing' end,completed_at=case when not exists(select 1 from public.import_rows where import_id=imp.id and status='pending') then now() end where id=imp.id;return processed;end $$;
revoke all on function private.process_import_batch(uuid,integer) from public,anon,authenticated;
create or replace function public.run_import_batch(p_import_id uuid,p_batch_size integer default 100) returns integer language sql security definer set search_path='' as $$ select private.process_import_batch(p_import_id,p_batch_size) $$;revoke all on function public.run_import_batch(uuid,integer) from public,anon,authenticated;grant execute on function public.run_import_batch(uuid,integer) to service_role;
create or replace function public.store_integration_credentials(p_integration_id uuid,p_user_id uuid,p_access text,p_refresh text,p_expires_at timestamptz) returns void language plpgsql security definer set search_path='' as $$ begin if not exists(select 1 from public.integrations where id=p_integration_id and user_id=p_user_id) then raise exception 'INTEGRATION_OWNERSHIP_MISMATCH';end if;insert into private.integration_credentials(integration_id,user_id,access_token_ciphertext,refresh_token_ciphertext,expires_at) values(p_integration_id,p_user_id,p_access,p_refresh,p_expires_at) on conflict(integration_id) do update set access_token_ciphertext=excluded.access_token_ciphertext,refresh_token_ciphertext=excluded.refresh_token_ciphertext,expires_at=excluded.expires_at,updated_at=now();end $$;revoke all on function public.store_integration_credentials(uuid,uuid,text,text,timestamptz) from public,anon,authenticated;grant execute on function public.store_integration_credentials(uuid,uuid,text,text,timestamptz) to service_role;
create or replace function public.delete_integration_credentials(p_integration_id uuid,p_user_id uuid) returns void language sql security definer set search_path='' as $$ delete from private.integration_credentials where integration_id=p_integration_id and user_id=p_user_id $$;revoke all on function public.delete_integration_credentials(uuid,uuid) from public,anon,authenticated;grant execute on function public.delete_integration_credentials(uuid,uuid) to service_role;
create index oauth_states_expiry_idx on public.oauth_states(expires_at) where used_at is null;create index moderation_status_time_idx on public.moderation_flags(status,created_at);
create policy imports_insert on public.imports for insert to authenticated with check(user_id=(select auth.uid()));create policy imports_update on public.imports for update to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));create policy import_rows_insert on public.import_rows for insert to authenticated with check(user_id=(select auth.uid()));grant insert,update on public.imports to authenticated;grant insert on public.import_rows to authenticated;
