create extension if not exists pgcrypto;
create type public.goal_status as enum ('draft','active','focus','later','paused','completed','abandoned','archived');
create type public.quest_status as enum ('planned','ready','in_progress','completed','skipped','cancelled','overdue');
create type public.measurement_model as enum ('numeric','currency','percentage','frequency','duration','milestones','binary','recurring','open_ended','composite','custom');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text not null check(length(display_name) between 1 and 80), timezone text not null default 'UTC', character_xp bigint not null default 0 check(character_xp>=0), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.user_preferences (user_id uuid primary key references auth.users(id) on delete cascade, theme text not null default 'system' check(theme in('system','light','dark')), gamification text not null default 'balanced' check(gamification in('full','balanced','minimal')), focus_limit smallint not null default 3 check(focus_limit between 1 and 10), locale text not null default 'en-GB', celebrations boolean not null default true, reduced_motion boolean not null default false);
create table public.goals (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, title text not null check(length(title) between 1 and 180), description text, category text not null default 'Other', status public.goal_status not null default 'active', measurement public.measurement_model not null, current_value numeric not null default 0, target_value numeric, unit text, currency char(3), deadline timestamptz, parent_id uuid references public.goals(id) on delete set null, priority text not null default 'normal' check(priority in('focus','high','normal','low','later')), metadata jsonb not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), archived_at timestamptz, check(target_value is null or target_value>=0));
create table public.goal_revisions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, goal_id uuid not null references public.goals(id) on delete cascade, previous_data jsonb not null, new_data jsonb not null, reason text, created_at timestamptz not null default now());
create table public.goal_progress_events (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, goal_id uuid not null references public.goals(id) on delete cascade, value numeric not null, delta numeric, note text, occurred_at timestamptz not null default now(), reversal_of uuid unique references public.goal_progress_events(id));
create table public.skills (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null check(length(name) between 1 and 100), category text not null default 'Other', parent_id uuid references public.skills(id) on delete set null, discovered_at timestamptz not null default now(), archived_at timestamptz, metadata jsonb not null default '{}', unique(user_id,name));
create table public.goal_skill_links (goal_id uuid not null references public.goals(id) on delete cascade, skill_id uuid not null references public.skills(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, weight numeric not null default 1 check(weight>0), primary key(goal_id,skill_id));
create table public.activities (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, description text not null check(length(description) between 1 and 500), duration_minutes integer check(duration_minutes between 0 and 100000), quantity numeric, unit text, effort text check(effort in('tiny','small','moderate','significant','major')), confidence text not null default 'self_reported' check(confidence in('self_reported','evidence_attached','integration_verified')), private_note text, occurred_at timestamptz not null default now(), created_at timestamptz not null default now(), idempotency_key text, unique(user_id,idempotency_key));
create table public.activity_goal_links (activity_id uuid not null references public.activities(id) on delete cascade, goal_id uuid not null references public.goals(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, primary key(activity_id,goal_id));
create table public.quests (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, title text not null check(length(title) between 1 and 180), description text, goal_id uuid references public.goals(id) on delete set null, status public.quest_status not null default 'ready', xp_reward integer not null default 25 check(xp_reward between 0 and 5000), due_at timestamptz, recurrence jsonb, evidence_required boolean not null default false, created_at timestamptz not null default now());
create table public.quest_skill_rewards (quest_id uuid not null references public.quests(id) on delete cascade, skill_id uuid not null references public.skills(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, xp integer not null check(xp between 0 and 5000), primary key(quest_id,skill_id));
create table public.quest_completions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, quest_id uuid not null references public.quests(id) on delete cascade, activity_id uuid not null references public.activities(id), completed_at timestamptz not null default now(), idempotency_key text not null, unique(quest_id), unique(user_id,idempotency_key));
create table public.habits (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, frequency jsonb not null, timezone text not null, xp_reward integer not null default 10 check(xp_reward between 0 and 500), goal_id uuid references public.goals(id) on delete set null, start_date date not null default current_date, end_date date, archived_at timestamptz);
create table public.habit_occurrences (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, habit_id uuid not null references public.habits(id) on delete cascade, local_date date not null, status text not null check(status in('complete','partial','skipped')), detail text, created_at timestamptz not null default now(), unique(habit_id,local_date));
create table public.xp_transactions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, skill_id uuid not null references public.skills(id) on delete restrict, source_type text not null check(source_type in('quest','activity','habit','achievement','milestone','integration','adjustment','import')), source_id uuid not null, amount integer not null check(amount between -5000 and 5000 and amount<>0), reason text not null check(length(reason)>0), confidence_level text not null default 'self_reported', created_at timestamptz not null default now(), reversal_of uuid unique references public.xp_transactions(id), metadata jsonb not null default '{}', unique(user_id,skill_id,source_type,source_id));
create table public.achievement_unlocks (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, achievement_key text not null, xp_awarded integer not null default 0, unlocked_at timestamptz not null default now(), metadata jsonb not null default '{}', unique(user_id,achievement_key));
create table public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, type text not null, title text not null, body text, read_at timestamptz, created_at timestamptz not null default now());
create index goals_user_status_idx on public.goals(user_id,status,updated_at desc); create index goal_events_goal_time_idx on public.goal_progress_events(goal_id,occurred_at desc); create index skills_user_parent_idx on public.skills(user_id,parent_id); create index activities_user_time_idx on public.activities(user_id,occurred_at desc); create index quests_user_due_idx on public.quests(user_id,status,due_at); create index xp_skill_time_idx on public.xp_transactions(skill_id,created_at desc); create index notifications_user_unread_idx on public.notifications(user_id,created_at desc) where read_at is null;

do $$ declare t text; begin foreach t in array array['profiles','user_preferences','goals','goal_revisions','goal_progress_events','skills','goal_skill_links','activities','activity_goal_links','quests','quest_skill_rewards','quest_completions','habits','habit_occurrences','xp_transactions','achievement_unlocks','notifications'] loop execute format('alter table public.%I enable row level security',t); execute format('create policy %I on public.%I for select to authenticated using ((select auth.uid()) = %I)',t||'_select',t,case when t in ('profiles') then 'id' when t='user_preferences' then 'user_id' else 'user_id' end); execute format('create policy %I on public.%I for insert to authenticated with check ((select auth.uid()) = %I)',t||'_insert',t,case when t='profiles' then 'id' when t='user_preferences' then 'user_id' else 'user_id' end); execute format('create policy %I on public.%I for update to authenticated using ((select auth.uid()) = %I) with check ((select auth.uid()) = %I)',t||'_update',t,case when t='profiles' then 'id' when t='user_preferences' then 'user_id' else 'user_id' end,case when t='profiles' then 'id' when t='user_preferences' then 'user_id' else 'user_id' end); end loop; end $$;
revoke delete on public.xp_transactions, public.goal_progress_events from authenticated;
grant select,insert,update,delete on all tables in schema public to authenticated;
revoke delete on public.xp_transactions, public.goal_progress_events from authenticated;

create or replace function public.skill_total_xp(p_skill_id uuid) returns bigint language sql stable security invoker set search_path='' as $$ select coalesce(sum(amount),0)::bigint from public.xp_transactions where skill_id=p_skill_id and user_id=(select auth.uid()) $$;
create or replace function public.complete_quest(p_quest_id uuid,p_idempotency_key text) returns uuid language plpgsql security invoker set search_path='' as $$ declare q public.quests; a_id uuid; c_id uuid; r record; begin select * into q from public.quests where id=p_quest_id and user_id=(select auth.uid()) for update; if not found then raise exception 'QUEST_NOT_FOUND'; end if; select id into c_id from public.quest_completions where quest_id=q.id; if c_id is not null then return c_id; end if; insert into public.activities(user_id,description,effort,occurred_at,idempotency_key) values((select auth.uid()),q.title,'moderate',now(),p_idempotency_key||':activity') returning id into a_id; insert into public.quest_completions(user_id,quest_id,activity_id,idempotency_key) values((select auth.uid()),q.id,a_id,p_idempotency_key) returning id into c_id; update public.quests set status='completed' where id=q.id; for r in select * from public.quest_skill_rewards where quest_id=q.id loop insert into public.xp_transactions(user_id,skill_id,source_type,source_id,amount,reason) values((select auth.uid()),r.skill_id,'quest',c_id,r.xp,'Quest completed: '||q.title) on conflict do nothing; end loop; return c_id; end $$;
revoke all on function public.complete_quest(uuid,text) from public,anon; grant execute on function public.complete_quest(uuid,text) to authenticated;
create or replace function public.prevent_immutable_mutation() returns trigger language plpgsql set search_path='' as $$ begin raise exception 'IMMUTABLE_LEDGER'; end $$;
create trigger xp_immutable before update or delete on public.xp_transactions for each row execute function public.prevent_immutable_mutation();
create trigger progress_immutable before update or delete on public.goal_progress_events for each row execute function public.prevent_immutable_mutation();

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path='' as $$ begin insert into public.profiles(id,display_name,timezone) values(new.id,coalesce(nullif(new.raw_user_meta_data->>'display_name',''),split_part(coalesce(new.email,'Adventurer'),'@',1)),'UTC'); insert into public.user_preferences(user_id) values(new.id); return new; end $$;
revoke all on function public.handle_new_user() from public,anon,authenticated;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
