alter table public.activities add column reversed_at timestamptz;
alter table public.quest_completions add column undone_at timestamptz;
alter table public.quest_completions drop constraint quest_completions_quest_id_key;
create unique index quest_one_active_completion_idx on public.quest_completions(quest_id) where undone_at is null;

create or replace function public.complete_quest(p_quest_id uuid,p_idempotency_key text) returns uuid language plpgsql security definer set search_path='' as $$ declare uid uuid:=(select auth.uid());q public.quests;a_id uuid;c_id uuid;r record;begin if uid is null then raise exception 'AUTHENTICATION_REQUIRED';end if;select * into q from public.quests where id=p_quest_id and user_id=uid for update;if not found then raise exception 'QUEST_NOT_FOUND';end if;select id into c_id from public.quest_completions where quest_id=q.id and undone_at is null;if c_id is not null then return c_id;end if;insert into public.activities(user_id,description,effort,occurred_at,idempotency_key) values(uid,q.title,'moderate',now(),p_idempotency_key||':activity') returning id into a_id;insert into public.quest_completions(user_id,quest_id,activity_id,idempotency_key) values(uid,q.id,a_id,p_idempotency_key) returning id into c_id;update public.quests set status='completed' where id=q.id;for r in select * from public.quest_skill_rewards where quest_id=q.id loop insert into public.xp_transactions(user_id,skill_id,source_type,source_id,amount,reason) values(uid,r.skill_id,'quest',c_id,r.xp,'Quest completed: '||q.title) on conflict do nothing;end loop;return c_id;end $$;

create or replace function public.undo_activity(p_activity_id uuid) returns void language plpgsql security definer set search_path='' as $$declare uid uuid:=(select auth.uid());tx record;begin if uid is null then raise exception 'AUTHENTICATION_REQUIRED';end if;update public.activities set reversed_at=coalesce(reversed_at,now()) where id=p_activity_id and user_id=uid and reversed_at is null;if not found then raise exception 'ACTIVITY_NOT_FOUND_OR_ALREADY_UNDONE';end if;for tx in select id from public.xp_transactions where user_id=uid and source_type='activity' and source_id=p_activity_id and reversal_of is null loop perform public.reverse_xp(tx.id,'Activity undone by user');end loop;insert into public.audit_events(user_id,event_type,object_type,object_id) values(uid,'activity.undone','activity',p_activity_id);end $$;

create or replace function public.undo_goal_progress(p_event_id uuid) returns uuid language plpgsql security definer set search_path='' as $$declare uid uuid:=(select auth.uid());original public.goal_progress_events;reversal_id uuid;prior_value numeric;begin if uid is null then raise exception 'AUTHENTICATION_REQUIRED';end if;select * into original from public.goal_progress_events where id=p_event_id and user_id=uid and reversal_of is null for update;if not found then raise exception 'PROGRESS_EVENT_NOT_FOUND';end if;select id into reversal_id from public.goal_progress_events where reversal_of=original.id;if reversal_id is not null then return reversal_id;end if;prior_value:=original.value-coalesce(original.delta,0);update public.goals set current_value=prior_value,updated_at=now() where id=original.goal_id and user_id=uid;insert into public.goal_progress_events(user_id,goal_id,value,delta,note,reversal_of) values(uid,original.goal_id,prior_value,-coalesce(original.delta,0),'Progress update undone',original.id) returning id into reversal_id;insert into public.audit_events(user_id,event_type,object_type,object_id,metadata) values(uid,'goal.progress_undone','goal',original.goal_id,jsonb_build_object('eventId',original.id));return reversal_id;end $$;

create or replace function public.undo_quest_completion(p_quest_id uuid) returns void language plpgsql security definer set search_path='' as $$declare uid uuid:=(select auth.uid());completion public.quest_completions;tx record;begin if uid is null then raise exception 'AUTHENTICATION_REQUIRED';end if;select * into completion from public.quest_completions where quest_id=p_quest_id and user_id=uid and undone_at is null for update;if not found then raise exception 'ACTIVE_COMPLETION_NOT_FOUND';end if;update public.quest_completions set undone_at=now() where id=completion.id;update public.activities set reversed_at=coalesce(reversed_at,now()) where id=completion.activity_id;update public.quests set status='ready' where id=p_quest_id and user_id=uid;for tx in select id from public.xp_transactions where user_id=uid and source_type='quest' and source_id=completion.id and reversal_of is null loop perform public.reverse_xp(tx.id,'Quest completion undone by user');end loop;insert into public.audit_events(user_id,event_type,object_type,object_id,metadata) values(uid,'quest.completion_undone','quest',p_quest_id,jsonb_build_object('completionId',completion.id));end $$;

revoke all on function public.undo_activity(uuid),public.undo_goal_progress(uuid),public.undo_quest_completion(uuid) from public,anon;grant execute on function public.undo_activity(uuid),public.undo_goal_progress(uuid),public.undo_quest_completion(uuid) to authenticated;

create or replace view public.user_progress_summary with(security_invoker=true) as select p.id user_id,coalesce(x.lifetime_xp,0)::bigint lifetime_xp,coalesce(x.weekly_xp,0)::bigint weekly_xp,coalesce(x.discovered_skills,0)::integer discovered_skills,coalesce(a.lifetime_activities,0)::integer lifetime_activities from public.profiles p left join lateral(select sum(amount) lifetime_xp,sum(amount) filter(where created_at>now()-interval '7 days') weekly_xp,count(distinct skill_id) discovered_skills from public.xp_transactions where user_id=p.id)x on true left join lateral(select count(*) lifetime_activities from public.activities where user_id=p.id and reversed_at is null)a on true;
create or replace view public.skill_xp_totals with(security_invoker=true) as select s.id skill_id,s.user_id,s.name,s.category,s.parent_id,s.discovered_at,coalesce(x.lifetime_xp,0)::bigint lifetime_xp,coalesce(x.recent_xp,0)::bigint recent_xp,coalesce(a.lifetime_activities,0)::integer lifetime_activities from public.skills s left join lateral(select sum(t.amount) lifetime_xp,sum(t.amount) filter(where t.created_at>now()-interval '30 days') recent_xp from public.xp_transactions t join public.skills ledger_skill on ledger_skill.id=t.skill_id where t.skill_id=s.id or ledger_skill.merged_into=s.id)x on true left join lateral(select count(distinct asl.activity_id) lifetime_activities from public.activity_skill_links asl join public.activities act on act.id=asl.activity_id where asl.skill_id=s.id and act.reversed_at is null)a on true where s.archived_at is null and s.merged_into is null;
