/* eslint-disable react-hooks/set-state-in-effect */
"use client";import Link from "next/link";import {useEffect,useState} from "react";
type ReferralData={code:{code:string;enabled:boolean};referrals:Array<{id:string;status:string;created_at:string;converted_at:string|null}>};
export default function Referrals(){
 const [data,setData]=useState<ReferralData|null>(null),[message,setMessage]=useState(""),[origin,setOrigin]=useState(""),[loading,setLoading]=useState(true),[failed,setFailed]=useState(false);
 const load=()=>{setLoading(true);return fetch("/api/v1/referrals").then(r=>{if(!r.ok)throw new Error();return r.json()}).then(body=>{setData(body.data||null);setFailed(false)}).catch(()=>setFailed(true)).finally(()=>setLoading(false))};
 useEffect(()=>{setOrigin(window.location.origin);fetch("/api/v1/referrals").then(r=>{if(!r.ok)throw new Error();return r.json()}).then(body=>{setData(body.data||null);setFailed(false)}).catch(()=>setFailed(true)).finally(()=>setLoading(false))},[]);
 const link=data?`${origin}/r/${data.code.code}`:"",copy=async()=>{try{await navigator.clipboard.writeText(link);setMessage("Referral link copied.")}catch{setMessage("The link could not be copied. Select it and copy it manually.")}};
 return <main className="onboard"><header><Link href="/app" className="onboard-logo">SkillTree IRL</Link><Link href="/app">Back to app</Link></header><section><div className="onboard-card"><p className="kicker">OPTIONAL REFERRALS</p><h1>Invite someone you care about</h1><p>Share SkillTree without turning progress into a popularity contest. Referrals can unlock cosmetics or Pro time, but never XP, levels, or achievements.</p>{message&&<p className="modal-tip" role="status">{message}</p>}{loading?<div className="live-loading" role="status"><i/><i/><i/></div>:failed?<div className="empty" role="alert"><h2>Referrals are temporarily unavailable</h2><p>Your referral record has not changed.</p><button className="primary" onClick={load}>Try again</button></div>:data?<div className="card side-card real-form"><label>Your referral link<input readOnly value={link}/></label><button className="primary" onClick={copy}>Copy link</button><h2>Referral status</h2>{data.referrals.length?data.referrals.map(item=><p key={item.id}><b>{item.status.replaceAll("_"," ")}</b><br/><small>{new Intl.DateTimeFormat("en-GB").format(new Date(item.created_at))}</small></p>):<p>No signups through this link yet.</p>}</div>:<div className="empty"><h2>No referral record is available</h2><p>Try reloading before sharing a link.</p><button className="primary" onClick={load}>Reload</button></div>}</div></section></main>;
}
